name: アークランズ

on: 
  workflow_dispatch:
    inputs:
      url:
        description: '株番号の入力'
        required: true
        default: '1234'
        
      nestock:
        description: '必要残り株数'
        required: true
        default: '100'
      instock:
        description: '1回当たりの注文株数'
        required: true
        default: '100'
      joken:
        description: '注文方法'
        required: true
        default: '寄付'
        type: choice
        options: ['寄付', '引け']
jobs:
  run-acranz-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v2
      
    - name: Python のセットアップ
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: 依存関係のインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Python スクリプトの実行
      run: python acranz.py
      env:
        INPUT_NESTOCK: ${{ github.event.inputs.nestock }}
        INPUT_INSTOCK: ${{ github.event.inputs.instock }}
        INPUT_JOKEN: ${{ github.event.inputs.joken }}
        INPUT_URL: ${{ github.event.inputs.url }}
