name: 自動クロス

on: 
  workflow_dispatch:
    inputs:
      shiten:
        description: '日興証券の支店番号を入力'
        required: true
        default: ''
      kouza:
        description: '日興証券の口座番号を入力'
        required: true
        default: ''
      loginpass:
        description: '日興証券のログインパスワードを入力'
        required: true
        default: ''
      torihikipass:
        description: '日興証券の取引パスワードを入力'
        required: true
        default: ''
      url:
        description: '一般信用売りしたい株番号の入力'
        required: true
        default: ''
        type: choice
        options: ['✅３月末優待', '  ▫️コロワイド(7616)', '  ▫️カッパ・クリエイト(7421)', '  ▫️ＲＹＯＤＥＮ(8084)', '  ▫️トリドールホールディングス(3397)', '✅４月末優待']        
      nestock:
        description: '必要残り株数'
        required: true
        default: '100'
      instock:
        description: '1回当たりの注文株数'
        required: true
        default: '100'
      joken:
        description: '注文方法'
        required: true
        default: '寄付'
        type: choice
        options: ['寄付', '引け']
jobs:
  run-acranz-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v2
      
    - name: Python のセットアップ
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: 依存関係のインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Python スクリプトの実行
      run: python acranz.py
      env:
        INPUT_SHITEN: ${{ github.event.inputs.shiten }}
        INPUT_KOUZA: ${{ github.event.inputs.kouza }}
        INPUT_LOGINPASS: ${{ github.event.inputs.loginpass }}
        INPUT_TORIHIKIPASS: ${{ github.event.inputs.torihikipass }}
        INPUT_NESTOCK: ${{ github.event.inputs.nestock }}
        INPUT_INSTOCK: ${{ github.event.inputs.instock }}
        INPUT_JOKEN: ${{ github.event.inputs.joken }}
        INPUT_URL: ${{ github.event.inputs.url }}
