name: Run Python Script

on: [push]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v2
      
    - name: Python のセットアップ
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: 依存関係のインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Python スクリプトの実行
      run: python acranz.py
